/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as LoginRouteImport } from './app/routes/login'
import { Route as MainRouteImport } from './app/routes/_main'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as AuthCallbackRouteImport } from './app/routes/auth.callback'
import { Route as MainProfileRouteImport } from './app/routes/_main/profile'
import { Route as MainMusicRouteImport } from './app/routes/_main/music'
import { Route as MainConfigIndexRouteImport } from './app/routes/_main/config/index'
import { Route as MainConfigUsageRouteImport } from './app/routes/_main/config/usage'
import { Route as MainConfigServerRouteImport } from './app/routes/_main/config/server'
import { Route as MainConfigMemoryRouteImport } from './app/routes/_main/config/memory'
import { Route as MainConfigMemoriesRouteImport } from './app/routes/_main/config/memories'
import { Route as MainConfigEconomyRouteImport } from './app/routes/_main/config/economy'
import { Route as MainConfigAiRouteImport } from './app/routes/_main/config/ai'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MainProfileRoute = MainProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainRoute,
} as any)
const MainMusicRoute = MainMusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => MainRoute,
} as any)
const MainConfigIndexRoute = MainConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => MainRoute,
} as any)
const MainConfigUsageRoute = MainConfigUsageRouteImport.update({
  id: '/config/usage',
  path: '/config/usage',
  getParentRoute: () => MainRoute,
} as any)
const MainConfigServerRoute = MainConfigServerRouteImport.update({
  id: '/config/server',
  path: '/config/server',
  getParentRoute: () => MainRoute,
} as any)
const MainConfigMemoryRoute = MainConfigMemoryRouteImport.update({
  id: '/config/memory',
  path: '/config/memory',
  getParentRoute: () => MainRoute,
} as any)
const MainConfigMemoriesRoute = MainConfigMemoriesRouteImport.update({
  id: '/config/memories',
  path: '/config/memories',
  getParentRoute: () => MainRoute,
} as any)
const MainConfigEconomyRoute = MainConfigEconomyRouteImport.update({
  id: '/config/economy',
  path: '/config/economy',
  getParentRoute: () => MainRoute,
} as any)
const MainConfigAiRoute = MainConfigAiRouteImport.update({
  id: '/config/ai',
  path: '/config/ai',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/music': typeof MainMusicRoute
  '/profile': typeof MainProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/config/ai': typeof MainConfigAiRoute
  '/config/economy': typeof MainConfigEconomyRoute
  '/config/memories': typeof MainConfigMemoriesRoute
  '/config/memory': typeof MainConfigMemoryRoute
  '/config/server': typeof MainConfigServerRoute
  '/config/usage': typeof MainConfigUsageRoute
  '/config/': typeof MainConfigIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/music': typeof MainMusicRoute
  '/profile': typeof MainProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/config/ai': typeof MainConfigAiRoute
  '/config/economy': typeof MainConfigEconomyRoute
  '/config/memories': typeof MainConfigMemoriesRoute
  '/config/memory': typeof MainConfigMemoryRoute
  '/config/server': typeof MainConfigServerRoute
  '/config/usage': typeof MainConfigUsageRoute
  '/config': typeof MainConfigIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_main': typeof MainRouteWithChildren
  '/login': typeof LoginRoute
  '/_main/music': typeof MainMusicRoute
  '/_main/profile': typeof MainProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_main/config/ai': typeof MainConfigAiRoute
  '/_main/config/economy': typeof MainConfigEconomyRoute
  '/_main/config/memories': typeof MainConfigMemoriesRoute
  '/_main/config/memory': typeof MainConfigMemoryRoute
  '/_main/config/server': typeof MainConfigServerRoute
  '/_main/config/usage': typeof MainConfigUsageRoute
  '/_main/config/': typeof MainConfigIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/music'
    | '/profile'
    | '/auth/callback'
    | '/config/ai'
    | '/config/economy'
    | '/config/memories'
    | '/config/memory'
    | '/config/server'
    | '/config/usage'
    | '/config/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/music'
    | '/profile'
    | '/auth/callback'
    | '/config/ai'
    | '/config/economy'
    | '/config/memories'
    | '/config/memory'
    | '/config/server'
    | '/config/usage'
    | '/config'
  id:
    | '__root__'
    | '/'
    | '/_main'
    | '/login'
    | '/_main/music'
    | '/_main/profile'
    | '/auth/callback'
    | '/_main/config/ai'
    | '/_main/config/economy'
    | '/_main/config/memories'
    | '/_main/config/memory'
    | '/_main/config/server'
    | '/_main/config/usage'
    | '/_main/config/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/profile': {
      id: '/_main/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainProfileRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/music': {
      id: '/_main/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MainMusicRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/config/': {
      id: '/_main/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof MainConfigIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/config/usage': {
      id: '/_main/config/usage'
      path: '/config/usage'
      fullPath: '/config/usage'
      preLoaderRoute: typeof MainConfigUsageRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/config/server': {
      id: '/_main/config/server'
      path: '/config/server'
      fullPath: '/config/server'
      preLoaderRoute: typeof MainConfigServerRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/config/memory': {
      id: '/_main/config/memory'
      path: '/config/memory'
      fullPath: '/config/memory'
      preLoaderRoute: typeof MainConfigMemoryRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/config/memories': {
      id: '/_main/config/memories'
      path: '/config/memories'
      fullPath: '/config/memories'
      preLoaderRoute: typeof MainConfigMemoriesRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/config/economy': {
      id: '/_main/config/economy'
      path: '/config/economy'
      fullPath: '/config/economy'
      preLoaderRoute: typeof MainConfigEconomyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/config/ai': {
      id: '/_main/config/ai'
      path: '/config/ai'
      fullPath: '/config/ai'
      preLoaderRoute: typeof MainConfigAiRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainMusicRoute: typeof MainMusicRoute
  MainProfileRoute: typeof MainProfileRoute
  MainConfigAiRoute: typeof MainConfigAiRoute
  MainConfigEconomyRoute: typeof MainConfigEconomyRoute
  MainConfigMemoriesRoute: typeof MainConfigMemoriesRoute
  MainConfigMemoryRoute: typeof MainConfigMemoryRoute
  MainConfigServerRoute: typeof MainConfigServerRoute
  MainConfigUsageRoute: typeof MainConfigUsageRoute
  MainConfigIndexRoute: typeof MainConfigIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainMusicRoute: MainMusicRoute,
  MainProfileRoute: MainProfileRoute,
  MainConfigAiRoute: MainConfigAiRoute,
  MainConfigEconomyRoute: MainConfigEconomyRoute,
  MainConfigMemoriesRoute: MainConfigMemoriesRoute,
  MainConfigMemoryRoute: MainConfigMemoryRoute,
  MainConfigServerRoute: MainConfigServerRoute,
  MainConfigUsageRoute: MainConfigUsageRoute,
  MainConfigIndexRoute: MainConfigIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
