/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as LoginRouteImport } from './app/routes/login'
import { Route as MainRouteImport } from './app/routes/_main'
import { Route as MainIndexRouteImport } from './app/routes/_main/index'
import { Route as AuthCallbackRouteImport } from './app/routes/auth.callback'
import { Route as MainUsersRouteImport } from './app/routes/_main/users'
import { Route as MainModerationRouteImport } from './app/routes/_main/moderation'
import { Route as MainGeneralRouteImport } from './app/routes/_main/general'
import { Route as MainDatabaseRouteImport } from './app/routes/_main/database'
import { Route as MainCooldownsRouteImport } from './app/routes/_main/cooldowns'
import { Route as MainBotsRouteImport } from './app/routes/_main/bots'
import { Route as MainAiRouteImport } from './app/routes/_main/ai'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MainUsersRoute = MainUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => MainRoute,
} as any)
const MainModerationRoute = MainModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => MainRoute,
} as any)
const MainGeneralRoute = MainGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => MainRoute,
} as any)
const MainDatabaseRoute = MainDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => MainRoute,
} as any)
const MainCooldownsRoute = MainCooldownsRouteImport.update({
  id: '/cooldowns',
  path: '/cooldowns',
  getParentRoute: () => MainRoute,
} as any)
const MainBotsRoute = MainBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => MainRoute,
} as any)
const MainAiRoute = MainAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/login': typeof LoginRoute
  '/ai': typeof MainAiRoute
  '/bots': typeof MainBotsRoute
  '/cooldowns': typeof MainCooldownsRoute
  '/database': typeof MainDatabaseRoute
  '/general': typeof MainGeneralRoute
  '/moderation': typeof MainModerationRoute
  '/users': typeof MainUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/ai': typeof MainAiRoute
  '/bots': typeof MainBotsRoute
  '/cooldowns': typeof MainCooldownsRoute
  '/database': typeof MainDatabaseRoute
  '/general': typeof MainGeneralRoute
  '/moderation': typeof MainModerationRoute
  '/users': typeof MainUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof MainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/login': typeof LoginRoute
  '/_main/ai': typeof MainAiRoute
  '/_main/bots': typeof MainBotsRoute
  '/_main/cooldowns': typeof MainCooldownsRoute
  '/_main/database': typeof MainDatabaseRoute
  '/_main/general': typeof MainGeneralRoute
  '/_main/moderation': typeof MainModerationRoute
  '/_main/users': typeof MainUsersRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_main/': typeof MainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai'
    | '/bots'
    | '/cooldowns'
    | '/database'
    | '/general'
    | '/moderation'
    | '/users'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/ai'
    | '/bots'
    | '/cooldowns'
    | '/database'
    | '/general'
    | '/moderation'
    | '/users'
    | '/auth/callback'
    | '/'
  id:
    | '__root__'
    | '/_main'
    | '/login'
    | '/_main/ai'
    | '/_main/bots'
    | '/_main/cooldowns'
    | '/_main/database'
    | '/_main/general'
    | '/_main/moderation'
    | '/_main/users'
    | '/auth/callback'
    | '/_main/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/users': {
      id: '/_main/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof MainUsersRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/moderation': {
      id: '/_main/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof MainModerationRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/general': {
      id: '/_main/general'
      path: '/general'
      fullPath: '/general'
      preLoaderRoute: typeof MainGeneralRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/database': {
      id: '/_main/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof MainDatabaseRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/cooldowns': {
      id: '/_main/cooldowns'
      path: '/cooldowns'
      fullPath: '/cooldowns'
      preLoaderRoute: typeof MainCooldownsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/bots': {
      id: '/_main/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof MainBotsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/ai': {
      id: '/_main/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof MainAiRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainAiRoute: typeof MainAiRoute
  MainBotsRoute: typeof MainBotsRoute
  MainCooldownsRoute: typeof MainCooldownsRoute
  MainDatabaseRoute: typeof MainDatabaseRoute
  MainGeneralRoute: typeof MainGeneralRoute
  MainModerationRoute: typeof MainModerationRoute
  MainUsersRoute: typeof MainUsersRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainAiRoute: MainAiRoute,
  MainBotsRoute: MainBotsRoute,
  MainCooldownsRoute: MainCooldownsRoute,
  MainDatabaseRoute: MainDatabaseRoute,
  MainGeneralRoute: MainGeneralRoute,
  MainModerationRoute: MainModerationRoute,
  MainUsersRoute: MainUsersRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
